language: python
python:
  - "3.6"
  # - "pypy3"  # might be faster that CPython for big compiles
install:
  - pip install codecov flake8==3.5
addons:
  apt:
    packages:
    - binutils
    - gcc
before_script:
  - flake8 . --count --show-source --statistics
  - flake8 . --exit-zero --max-complexity=15
script: coverage run -m unittest discover
after_success: codecov
