"""Integration test driver for the compiler.

This module defines a metaclass which generates test cases from files on disk,
and a test class based off that metaclass. For each file that matches
"tests/feature_tests/*.c", a test function is generated.

If the C file contains a line of the form:

// Return: ###

Then, the test expects the main() in that test file to return the value
"###". If no such line exists, the default expected return value is 0.

If the C file contains line(s) of the form:
// Issue: ____

Then, the test expects compiliation to fail with an error or warning whose
message contains the string "____".

"""

from errors import error_collector
import glob
import pathlib
import subprocess
import shivyc
import unittest


def compile_with_shivyc(test_file_name):
    """Compile given file with ShivyC.

    Errors are saved in the error collector.

    """
    # Mock out arguments to ShivyC call
    class MockArguments:
        filename = test_file_name
        show_il = False
        show_reg_alloc_perf = False
        variables_on_stack = False

    shivyc.get_arguments = lambda: MockArguments()

    # Mock out error collector functions
    error_collector.show = lambda: True

    shivyc.main()


class MetaIntegrationTests(type):
    """Metaclass for creating integration tests."""

    def __new__(meta, name, bases, dct):
        """Create a class with the desired functions."""
        # Dictionary mapping test names to issues they are expected to raise.

        def generate_test(test_file_name):
            def test_function(self):
                # Read test parameters from test file
                with open(test_file_name) as f:
                    ret_val = 0
                    issues = []

                    for line in f.readlines():
                        ret_mark = "// Return:"
                        issue_mark = "// Issue:"

                        if line.strip().startswith(ret_mark):
                            ret_val = int(line.split(ret_mark)[-1])
                        elif line.strip().startswith(issue_mark):
                            issues.append(line.split(issue_mark)[-1])

                compile_with_shivyc(test_file_name)

                if not issues:
                    self.assertEqual(error_collector.issues, [])
                    self.assertEqual(subprocess.call(["./out"]), ret_val)
                else:
                    clean_issues = list(map(lambda x: x.strip(), issues))

                    front_strip = len(test_file_name) + 1
                    clean_actual = list(map(lambda x: str(x)[front_strip:],
                                            error_collector.issues))

                    self.assertListEqual(clean_issues, clean_actual)
                    self.assertEqual(subprocess.call(["./out"]), ret_val)

            return test_function

        test_file_names = glob.glob("tests/feature_tests/*.c")
        for test_file_name in test_file_names:
            short_name = test_file_name.split("/")[-1][:-2]
            test_func_name = "test_" + short_name
            dct[test_func_name] = generate_test(test_file_name)

        return super().__new__(meta, name, bases, dct)


class IntegrationTests(unittest.TestCase, metaclass=MetaIntegrationTests):
    """Integration tests for the compiler.

    The feature_tests are all generated by the metaclass above. The
    general_tests are manually added and tested here.

    """

    def setUp(self):
        """Clear error collector before each test."""
        error_collector.clear()

    def test_count(self):
        """Test the Count.c program from the first pset of CPSC 223 at Yale."""

        rel_dir = "general_tests/count"
        dir = str(pathlib.Path(__file__).parent.joinpath(rel_dir))

        # Remove leftover files from last test
        rm = "rm -f {0}/gcc_out {0}/out {0}/shivyc_output {0}/gcc_output"
        subprocess.run(rm, shell=True, check=True)

        # Compile Count.c with ShivyC
        compile_with_shivyc(dir + "/Count.c")
        self.assertEqual(error_collector.issues, [])

        # Compile Count.c with gcc
        gcc_compile = "gcc {0}/Count.c -o gcc_out".format(dir)
        subprocess.run(gcc_compile, shell=True, check=True)

        # Run ShivyC executable on sample input
        shivyc_run = "./out < {0}/input.c > {0}/shivyc_output".format(dir)
        subprocess.run(shivyc_run, shell=True, check=True)

        # Run gcc executable on sample input
        gcc_run = "./gcc_out < {0}/input.c > {0}/gcc_output".format(dir)
        subprocess.run(gcc_run, shell=True, check=True)

        diff = "diff {0}/gcc_output {0}/shivyc_output".format(dir)
        subprocess.run(diff, shell=True, check=True)
