void    *memchr(const void *, int, unsigned long);
int      memcmp(const void *, const void *, unsigned long);
void    *memcpy(void *, const void *, unsigned long);
void    *memmove(void *, const void *, unsigned long);
void    *memset(void *, int, unsigned long);
char    *strcat(char *, const char *);
char    *strchr(const char *, int);
int      strcmp(const char *, const char *);
int      strcoll(const char *, const char *);
char    *strcpy(char *, const char *);
unsigned long    strcspn(const char *, const char *);
char    *strdup(const char *);
char    *strerror(int);
unsigned long    strlen(const char *);
char    *strncat(char *, const char *, unsigned long);
int      strncmp(const char *, const char *, unsigned long);
char    *strncpy(char *, const char *, unsigned long);
char    *strpbrk(const char *, const char *);
char    *strrchr(const char *, int);
unsigned long    strspn(const char *, const char *);
char    *strstr(const char *, const char *);
char    *strtok(char *, const char *);
char    *strtok_r(char *, const char *, char **);
unsigned long    strxfrm(char *, const char *, unsigned long);
