name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils gcc
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov flake8==7.3.0 coverage
    
    - name: Lint with flake8 (show source and statistics)
      run: |
        flake8 . --count --show-source --statistics
    
    - name: Lint with flake8 (complexity check)
      run: |
        flake8 . --exit-zero --max-complexity=15
    
    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false 